name: test
description: テストです
body:
  - type: dropdown
    id: hoge
    attributes:
      label: hoge
      multiple: true
      options:
        - こんにちは
        - さようなら
      default: 0
    validations:
      required: false
  - type: checkboxes
    id: field
    attributes:
      label: ヤッホ-
      options:
        - label: hello
          required: true
        - label: yaya
    validations:
      required: false
